name: Build & Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -covermode=count -coverprofile=profile.cov ./pkg/...
        
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        GO111MODULE=off go get github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github

    - name: Build Windows images from Dockerfile
      run: |
        export REGISTRY=test
        export DOCKER_CLI_EXPERIMENTAL=enabled
        export OUTPUT_TYPE=docker
        make build-container-windows-1809
        make build-container-windows-20H2
        make build-container-windows-2022
