name: Lint Helm Charts

on:
  pull_request:
    branches:
      - master
    paths:
      - "helm/provisioner/**"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0

      - name: Set-up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest

      - name: Set-up Python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
        with:
          python-version: "3.x"

      - name: Set-up chart-testing
        uses: helm/chart-testing-action@e8788873172cb653a90ca2e819d79d65a66d4e76

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs=helm --charts=helm/provisioner --lint-conf=helm/lintconf.yaml --check-version-increment=false --validate-maintainers=false

      - name: Create Kind cluster
        uses: helm/kind-action@d8ccf8fb623ce1bb360ae2f45f323d9d5c5e9f00

      - name: Run chart-testing (install)
        run: ct install --chart-dirs=helm --charts=helm/provisioner
